#! /bin/bash

set -e

eval "$(cat scripts/env)"

INIT_FILE=$(mktemp)
echo "Init file: $INIT_FILE"
cat $INIT_FILE

vault init > $INIT_FILE

for i in {1..3};do
  key=$(cat $INIT_FILE | grep -i "unseal key $i:" | awk '{print $4}')
  vault unseal $key
done

token=$(cat $INIT_FILE | grep -i "root token:" | awk '{print $4}')
vault auth $token

vault audit-enable file path=/var/log/vault_audit.log

vault mount ssh
vault write ssh/roles/otp_ops key_type=otp default_user=ops cidr_list=127.0.0.0/8,172.0.0.0/8,192.0.0.0/8

vault mount mysql

# vault auth-enable github
# vault write auth/github/config organization=hashicorp
# vault write auth/github/config base_url=https://github.mydomain.com/api/v3/
# vault write auth/github/map/teams/root value=root

